#!/usr/bin/env bash
#### MainsailOS Specific Tweaks for armbian images
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2023 - till today
#### https://github.com/mainsail-crew/MainsailOS
####
#### This File is distributed under GPLv3
####

# shellcheck enable=require-variable-braces
# Source error handling, leave this in place
set -Ee

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

## Helper functions
gen_root_pw() {
    tr -dc "[:alnum:]" < /dev/urandom | head -c 50
}

## Clean up
## Step 1: Remove autologin and lock root account
if [[ -f "/etc/systemd/system/getty@.service.d/override.conf" ]]; then
    rm -f /etc/systemd/system/getty@.service.d/override.conf
fi
## END

## Step 2: Disable autologin on serial console
if [[ -f "/etc/systemd/system/serial-getty@.service.d/override.conf" ]]; then
    sed -i 's/--autologin root //' /etc/systemd/system/serial-getty@.service.d/override.conf
fi
## END

## Step 3: Delete root passwd
### Deleting root passwd doesn't let you unlock the account
sudo passwd -d root
## END

## Step 4: Lock root account
sudo passwd -l root
## END

## Step 5: Replace build-time blanket sudo with targeted NOPASSWD
# Remove the build-time blanket rule
sed -i '/'"${BASE_USER}"' ALL=(ALL:ALL) NOPASSWD:ALL/d' /etc/sudoers

# Add targeted NOPASSWD rules for RetroPie menu operations
# (wifi config, bluetooth, retropie-setup, runcommand, etc.)
cat > /etc/sudoers.d/retromi-nopasswd << SUDOEOF
# RetroMi: allow pi to run RetroPie tools without password prompt
${BASE_USER} ALL=(ALL) NOPASSWD: /home/${BASE_USER}/Retropie-Setup/retropie_setup.sh
${BASE_USER} ALL=(ALL) NOPASSWD: /home/${BASE_USER}/Retropie-Setup/retropie_packages.sh *
${BASE_USER} ALL=(ALL) NOPASSWD: /opt/retropie/supplementary/runcommand/runcommand.sh *
${BASE_USER} ALL=(ALL) NOPASSWD: /sbin/iwlist *
${BASE_USER} ALL=(ALL) NOPASSWD: /sbin/wpa_cli *
${BASE_USER} ALL=(ALL) NOPASSWD: /usr/sbin/rfkill *
${BASE_USER} ALL=(ALL) NOPASSWD: /usr/bin/nmcli *
${BASE_USER} ALL=(ALL) NOPASSWD: /usr/sbin/nmtui
${BASE_USER} ALL=(ALL) NOPASSWD: /usr/bin/apt-get *
${BASE_USER} ALL=(ALL) NOPASSWD: /usr/bin/systemctl *
${BASE_USER} ALL=(ALL) NOPASSWD: /sbin/shutdown *
${BASE_USER} ALL=(ALL) NOPASSWD: /sbin/reboot
SUDOEOF
chmod 440 /etc/sudoers.d/retromi-nopasswd
## END
