#!/usr/bin/env bash
#### Smartpad Specific Tweaks for armbian images
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2023 - till today
#### https://github.com/KwadFan
####
#### This File is distributed under GPLv3
####

# shellcheck enable=require-variable-braces
# Source error handling, leave this in place
set -Ee

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

[[ -n "${SMARTPAD_CONFIG_TXT_FILE}" ]] || SMARTPAD_CONFIG_TXT_FILE="/boot/armbianEnv.txt"
[[ -n "${SMARTPAD_PLYMOUTH_REPO}" ]] || SMARTPAD_PLYMOUTH_REPO="https://github.com/Yumi-Lab/plymouth-themes.git"
[[ -n "${SMARTPAD_PLYMOUTH_THEME}" ]] || SMARTPAD_PLYMOUTH_THEME="pixels"

sudo apt-get update
sudo apt-get install plymouth -y

### Helper func
is_board_type() {
    local board releasefile
    board=""
    releasefile="/etc/armbian-release"
    if [[ -f "${releasefile}" ]]; then
        board="$(grep "BOARD=" "${releasefile}" | cut -d'=' -f2)"
    fi
    echo "${board}"
}

echo_green "Apply SmartPad specific patches..."

unpack /filesystem/root /
if [[ -f /etc/X11/xorg.conf.d/03-smartpad-rotate-touch.conf ]]; then
    rm -fv /etc/X11/xorg.conf.d/03-smartpad-rotate-touch.conf
fi

echo_green "Apply SmartPad specific patches... [DONE]"

### Install plymouth theme and install yumi Plymouth repository
echo_green "Install Yumi Lab Plymouth theme on SmartPad..."
# Vérifier que la variable SMARTPAD_PLYMOUTH_REPO est définie
if [[ -z "${SMARTPAD_PLYMOUTH_REPO}" ]]; then
    echo_red "La variable SMARTPAD_PLYMOUTH_REPO n'est pas définie. Annulation."
    exit 1
fi
pushd "/home/${BASE_USER}" &>/dev/null

# Path to the directory to check and delete
DIR="/home/pi/plymouth-themes"

# Check if the directory exists
if [[ -d "${DIR}" ]]; then
    # Delete the directory and all its contents
    rm -rf "${DIR}"
    echo "The directory ${DIR} has been successfully deleted."
else
    echo "The directory ${DIR} does not exist."
fi

echo "download git plymouth ${SMARTPAD_PLYMOUTH_REPO}"
if ! sudo -u "${BASE_USER}" git clone "${SMARTPAD_PLYMOUTH_REPO}"; then
    echo_red "Clone error. Check URL: ${SMARTPAD_PLYMOUTH_REPO}"
    exit 1
fi

echo "install plymouth"
dest="/usr/share/plymouth/themes/"
src="/home/${BASE_USER}/$(basename "${SMARTPAD_PLYMOUTH_REPO/.git/}")"
src="${src}/pack_3/pixels"
if [[ -d "${src}" ]]; then
    sudo cp -vr "${src}" "${dest}"
fi
echo_green "Set default theme to ${SMARTPAD_PLYMOUTH_THEME} ..."
#sudo plymouth-set-default-theme "${SMARTPAD_PLYMOUTH_THEME}"
sudo plymouth-set-default-theme -R pixels
sudo update-initramfs -u
popd &>/dev/null
echo_green "Set default theme to ${SMARTPAD_PLYMOUTH_THEME} ...(DONE)"
echo_green "Install Yumi Lab Plymouth theme on SmartPad... [DONE]"

echo_green "Enable first boot service..."
systemctl_if_exists enable firstboot.service
