#!/usr/bin/env bash
#### Smartpad Specific Tweaks for armbian images
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2023 - till today
#### https://github.com/KwadFan
####
#### This File is distributed under GPLv3
####

# shellcheck enable=require-variable-braces
# Source error handling, leave this in place
set -Ee

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap


echo_green "Update RetroArch..."
#unpack fix retroarch
unpack /filesystem/home/pi /home/pi
cd /home/pi
mkdir retroarch
sudo unzip Retroarch-fix.zip -d /home/pi/retroarch
# create emulators folder
sudo mkdir -p /opt/retropie/emulators
sudo mkdir -p /opt/retropie/configs/all/retroarch-joypads
unpack /filesystem/opt/retropie/configs/all/retroarch-joypads /opt/retropie/configs/all/retroarch-joypads
# copy
sudo cp -r /home/pi/retroarch/opt/retropie/emulators/* /opt/retropie/emulators/

#create symbolic links
ln -s "/opt/retropie/configs/all/retroarch/overlay" "/opt/retropie/emulators/retroarch/overlays"
ln -s "/opt/retropie/configs/all/retroarch/assets" "/opt/retropie/emulators/retroarch/assets"
ln -s "/opt/retropie/configs/all/retroarch/shaders" "/opt/retropie/emulators/retroarch/shader"
#set access
chmod 777 -R /home/pi/RetroPie/
#sudo apt-get install xpad
echo_green "Enable RetroArch...(DONE)"

