#!/usr/bin/env bash
# Shebang for better file detection
# shellcheck enable=require-variable-braces
# shellcheck disable=SC2034



# Image source
DOWNLOAD_URL_CHECKSUM="${DOWNLOAD_BASE_URL}/yumi-smartpione-retropie-light.img.xz.sha256"
DOWNLOAD_URL_IMAGE="${DOWNLOAD_BASE_URL}/yumi-smartpione-retropie-light.img.xz"

BASE_IMAGE_ENLARGEROOT=6000
MODULES="base(pkgupgrade,udev_fix,armbian(armbian_net,yumios,is_req_preinstall,filebroswer))"

# export Variables
export BASE_ARCH
export DOWNLOAD_URL_CHECKSUM
export DOWNLOAD_URL_IMAGE
