#!/usr/bin/env bash
#### Smartpad Specific Tweaks for armbian images
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2023 - till today
#### https://github.com/KwadFan
####
#### This File is distributed under GPLv3
####

# shellcheck enable=require-variable-braces
# Source error handling, leave this in place
set -Ee

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap



echo_green "Add Music..."
unpack /filesystem/home/pi/music_setup /home/pi/music_setup
cd /home/pi/music_setup 
chmod +x setup.sh 
./setup.sh 
unpack /filesystem/home/pi/RetroPie/roms/music /home/pi/RetroPie/roms/music
echo_green "Add Music...(DONE)"
