#!/usr/bin/env bash
#### Smartpad Specific Tweaks for armbian images
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2023 - till today
#### https://github.com/KwadFan
####
#### This File is distributed under GPLv3
####

# shellcheck enable=require-variable-braces
# Source error handling, leave this in place
set -Ee

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap



echo_green "Add Music..."

unpack /filesystem/home/pi/RetroPie/roms/music /
#Now we need to download the file. Enter the following command into the terminal:
wget https://installtekz.com/downloads/musicpi/music_setup.tar.gz 
#Next we need to uncompress the file with the following command:
tar -xvzf music_setup.tar.gz 
#Once the file is uncompressed, we need to move in to the “music_setup” directory with the next command:
cd music_setup 
#Now we need to make the setup script executable:
chmod +x setup.sh 
#And finally, run the script:
./setup.sh 
#Set access all
sudo chmod 777 -R /filesystem/home/pi/RetroPie
sudo chmod 777 -R /opt/retropie

echo_green "Add Music..."
