#!/usr/bin/env bash
#### Smartpad Specific Tweaks for armbian images
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2023 - till today
#### https://github.com/KwadFan
####
#### This File is distributed under GPLv3
####

# shellcheck enable=require-variable-braces
# Source error handling, leave this in place
set -Ee

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap



echo_green "Add Music..."

wget -P /home/pi/RetroPie-Setup/ext/dev_philcomm/scriptmodules/supplementary/ "https://raw.githubusercontent.com/OfficialPhilcomm/retropie-music/master/retropie-music.sh"
unpack /filesystem/home/pi/RetroPie/roms/music /home/pi/RetroPie/roms/music
chmod 777 -R /home/pi/RetroPie/roms/music
cd /home/pi/RetroPie-Setup/ext/dev_philcomm/scriptmodules/supplementary
sudo ./retropie-music.sh

echo_green "Add Music...(DONE)"
