#!/usr/bin/env bash
#### Smartpad Specific Tweaks for armbian images
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2023 - till today
#### https://github.com/KwadFan
####
#### This File is distributed under GPLv3
####

# shellcheck enable=require-variable-braces
# Source error handling, leave this in place
set -Ee

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap



echo_green "Emulationstation Splash Screen..."
unpack /filesystem/opt/retropie/supplementary/emulationstation/resources/ /opt/retropie/supplementary/emulationstation/resources/
chmod 777 -R /opt/retropie
echo_green "Emulationstation Splash Screen...(DONE)"

echo_green "Emulationstation Menu..."
unpack /filesystem/home/pi/RetroPie/retropiemenu /home/pi/RetroPie/retropiemenu
echo_green "Emulationstation Menu... (DONE)"


echo_green "Emulationstation Theme Epic-Cody..."
cd /etc/emulationstation/themes
sudo git clone https://github.com/CodyV59/es-theme-epic-cody-RG351V.git --branch master
echo_green "Emulationstation Theme Epic-Cody... (DONE)"

echo_green "Emulationstation Theme Epicnoir..."
cd /etc/emulationstation/themes
sudo git clone https://github.com/c64-dev/es-epicnoir.git --branch master
echo_green "Emulationstation Theme Epicnoir... (DONE)"

