#!/usr/bin/env bash
#### Smartpad Specific Tweaks for armbian images
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2023 - till today
#### https://github.com/KwadFan
####
#### This File is distributed under GPLv3
####

# shellcheck enable=require-variable-braces
# Source error handling, leave this in place
set -Ee

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

apt-get install -y --no-install-recommends p7zip-full

echo_green "Emulationstation Splash Screen..."
mkdir -p /opt/retropie/supplementary/emulationstation/resources/
unpack /filesystem/opt/retropie/supplementary/emulationstation/resources/ /opt/retropie/supplementary/emulationstation/resources/
chmod 777 -R /opt/retropie
echo_green "Emulationstation Splash Screen...(DONE)"

echo_green "Emulationstation Menu..."
unpack /filesystem/home/pi/RetroPie/retropiemenu /home/pi/RetroPie/retropiemenu
echo_green "Emulationstation Menu... (DONE)"

#echo_green "Emulationstation Theme Epicnoir..."
#cd /etc/emulationstation/themes
#sudo git clone https://github.com/c64-dev/es-epicnoir.git --branch master
#echo_green "Emulationstation Theme Epicnoir... (DONE)"

mkdir -p /etc/emulationstation/themes/
unpack /filesystem/etc/emulationstation/themes/ /etc/emulationstation/themes/
cd /etc/emulationstation/themes/
7z x themes.zip.001
rm themes.zip*
sudo chmod 777 -R /etc/emulationstation/themes/

# Deploy pre-configured ES settings (theme selection + defaults)
echo_green "Setting default EmulationStation theme (Switch_Black_v2)..."
mkdir -p /opt/retropie/configs/all/emulationstation
unpack /filesystem/opt/retropie/configs/all/emulationstation /opt/retropie/configs/all/emulationstation
chown -R pi:pi /opt/retropie/configs/all/emulationstation
echo_green "Default ES theme configured. (DONE)"
