#!/usr/bin/env bash
#### Smartpad Specific Tweaks for armbian images
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2023 - till today
#### https://github.com/KwadFan
####
#### This File is distributed under GPLv3
####

# shellcheck enable=require-variable-braces
# Source error handling, leave this in place
set -Ee

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap


echo_green "install filebroswer..."
sudo curl -fsSL https://raw.githubusercontent.com/filebrowser/get/master/get.sh | bash

echo "configure filebrowser (noauth)"
cat << 'EOF' | sudo tee /usr/local/bin/start_filebrowser.sh
#!/bin/bash
filebrowser config init -d /var/lib/filebrowser.db
filebrowser config set -d /var/lib/filebrowser.db \
    --address 0.0.0.0 \
    --port 80 \
    --auth.method=noauth \
    --root /home/pi/RetroPie
filebrowser -d /var/lib/filebrowser.db
EOF

sudo chmod +x /usr/local/bin/start_filebrowser.sh

cat << 'EOF' | sudo tee /etc/systemd/system/filebrowser.service
[Unit]
Description=FileBrowser Service
After=network.target

[Service]
ExecStart=/usr/local/bin/start_filebrowser.sh
Restart=always
User=root
Group=root

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable filebrowser.service

sudo chmod 777 -R /home/pi/RetroPie/
echo_green "install filebroswer...(DONE)"
