#!/usr/bin/env bash
#### USB Auto Mount — bind-mount USB/RetroMi/ over ~/RetroPie
####
#### This File is distributed under GPLv3
####

# shellcheck enable=require-variable-braces
# Source error handling, leave this in place
set -Ee

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap


echo_green "Enable USB Auto Mount..."
git clone https://github.com/Yumi-Lab/auto-mount-retromi.git
cd auto-mount-retromi/
sudo chmod +x ./CONFIGURE.sh
sudo ./CONFIGURE.sh
echo_green "Enable USB Auto Mount...(DONE)"
